package concertbooking;

import javax.swing.JOptionPane;

/**
 *
 * @authors Patrick Crossan B00663255 Ciaran Jordan B00663523
 */
public class ConcertUI extends javax.swing.JFrame
{
    private String name;
    private String seat;
    private String concert;
    private String concertDate;
    private double goldPrice;
    private double silverPrice;
    private double bronzePrice;
    /**
     * Creates new form ConcertUI
     */
    public ConcertUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        concertPanel = new javax.swing.JPanel();
        gA10 = new javax.swing.JButton();
        gA9 = new javax.swing.JButton();
        gA8 = new javax.swing.JButton();
        gA7 = new javax.swing.JButton();
        gA6 = new javax.swing.JButton();
        gB6 = new javax.swing.JButton();
        gB7 = new javax.swing.JButton();
        gB8 = new javax.swing.JButton();
        gB9 = new javax.swing.JButton();
        gB10 = new javax.swing.JButton();
        gC10 = new javax.swing.JButton();
        gC9 = new javax.swing.JButton();
        gC8 = new javax.swing.JButton();
        gC7 = new javax.swing.JButton();
        gC6 = new javax.swing.JButton();
        gA5 = new javax.swing.JButton();
        gA4 = new javax.swing.JButton();
        gA3 = new javax.swing.JButton();
        gA2 = new javax.swing.JButton();
        gA1 = new javax.swing.JButton();
        gB1 = new javax.swing.JButton();
        gB2 = new javax.swing.JButton();
        gB3 = new javax.swing.JButton();
        gB4 = new javax.swing.JButton();
        gB5 = new javax.swing.JButton();
        gC5 = new javax.swing.JButton();
        gC4 = new javax.swing.JButton();
        gC3 = new javax.swing.JButton();
        gC2 = new javax.swing.JButton();
        gC1 = new javax.swing.JButton();
        sD10 = new javax.swing.JButton();
        sD9 = new javax.swing.JButton();
        sD8 = new javax.swing.JButton();
        sD7 = new javax.swing.JButton();
        sD6 = new javax.swing.JButton();
        sE6 = new javax.swing.JButton();
        sE7 = new javax.swing.JButton();
        sE8 = new javax.swing.JButton();
        sE9 = new javax.swing.JButton();
        sE10 = new javax.swing.JButton();
        sD5 = new javax.swing.JButton();
        sD4 = new javax.swing.JButton();
        sD3 = new javax.swing.JButton();
        sD2 = new javax.swing.JButton();
        sD1 = new javax.swing.JButton();
        sE1 = new javax.swing.JButton();
        sE2 = new javax.swing.JButton();
        sE3 = new javax.swing.JButton();
        sE4 = new javax.swing.JButton();
        sE5 = new javax.swing.JButton();
        sF1 = new javax.swing.JButton();
        sF2 = new javax.swing.JButton();
        sF3 = new javax.swing.JButton();
        sF4 = new javax.swing.JButton();
        sF5 = new javax.swing.JButton();
        sF6 = new javax.swing.JButton();
        sF7 = new javax.swing.JButton();
        sF8 = new javax.swing.JButton();
        sF9 = new javax.swing.JButton();
        sF10 = new javax.swing.JButton();
        bG10 = new javax.swing.JButton();
        bG9 = new javax.swing.JButton();
        bG8 = new javax.swing.JButton();
        bG7 = new javax.swing.JButton();
        bG6 = new javax.swing.JButton();
        bG5 = new javax.swing.JButton();
        bG4 = new javax.swing.JButton();
        bG3 = new javax.swing.JButton();
        bG2 = new javax.swing.JButton();
        bG1 = new javax.swing.JButton();
        bH1 = new javax.swing.JButton();
        bH2 = new javax.swing.JButton();
        bH3 = new javax.swing.JButton();
        bH4 = new javax.swing.JButton();
        bH5 = new javax.swing.JButton();
        bH6 = new javax.swing.JButton();
        bH7 = new javax.swing.JButton();
        bH8 = new javax.swing.JButton();
        bH9 = new javax.swing.JButton();
        bH10 = new javax.swing.JButton();
        bI10 = new javax.swing.JButton();
        bI9 = new javax.swing.JButton();
        bI8 = new javax.swing.JButton();
        bI7 = new javax.swing.JButton();
        bI6 = new javax.swing.JButton();
        bI5 = new javax.swing.JButton();
        bI4 = new javax.swing.JButton();
        bI3 = new javax.swing.JButton();
        bI2 = new javax.swing.JButton();
        bI1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        concertPanel.setBackground(new java.awt.Color(255, 255, 255));

        gA10.setBackground(new java.awt.Color(204, 204, 0));
        gA10.setForeground(new java.awt.Color(204, 204, 0));
        gA10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClick(evt);
            }
        });

        gA9.setBackground(new java.awt.Color(204, 204, 0));
        gA9.setForeground(new java.awt.Color(204, 204, 0));

        gA8.setBackground(new java.awt.Color(204, 204, 0));
        gA8.setForeground(new java.awt.Color(204, 204, 0));

        gA7.setBackground(new java.awt.Color(204, 204, 0));
        gA7.setForeground(new java.awt.Color(204, 204, 0));

        gA6.setBackground(new java.awt.Color(204, 204, 0));
        gA6.setForeground(new java.awt.Color(204, 204, 0));

        gB6.setBackground(new java.awt.Color(204, 204, 0));
        gB6.setForeground(new java.awt.Color(204, 204, 0));

        gB7.setBackground(new java.awt.Color(204, 204, 0));
        gB7.setForeground(new java.awt.Color(204, 204, 0));

        gB8.setBackground(new java.awt.Color(204, 204, 0));
        gB8.setForeground(new java.awt.Color(204, 204, 0));

        gB9.setBackground(new java.awt.Color(204, 204, 0));
        gB9.setForeground(new java.awt.Color(204, 204, 0));

        gB10.setBackground(new java.awt.Color(204, 204, 0));
        gB10.setForeground(new java.awt.Color(204, 204, 0));

        gC10.setBackground(new java.awt.Color(204, 204, 0));
        gC10.setForeground(new java.awt.Color(204, 204, 0));

        gC9.setBackground(new java.awt.Color(204, 204, 0));
        gC9.setForeground(new java.awt.Color(204, 204, 0));

        gC8.setBackground(new java.awt.Color(204, 204, 0));
        gC8.setForeground(new java.awt.Color(204, 204, 0));

        gC7.setBackground(new java.awt.Color(204, 204, 0));
        gC7.setForeground(new java.awt.Color(204, 204, 0));

        gC6.setBackground(new java.awt.Color(204, 204, 0));
        gC6.setForeground(new java.awt.Color(204, 204, 0));

        gA5.setBackground(new java.awt.Color(204, 204, 0));
        gA5.setForeground(new java.awt.Color(204, 204, 0));

        gA4.setBackground(new java.awt.Color(204, 204, 0));
        gA4.setForeground(new java.awt.Color(204, 204, 0));

        gA3.setBackground(new java.awt.Color(204, 204, 0));
        gA3.setForeground(new java.awt.Color(204, 204, 0));

        gA2.setBackground(new java.awt.Color(204, 204, 0));
        gA2.setForeground(new java.awt.Color(204, 204, 0));

        gA1.setBackground(new java.awt.Color(204, 204, 0));
        gA1.setForeground(new java.awt.Color(204, 204, 0));

        gB1.setBackground(new java.awt.Color(204, 204, 0));
        gB1.setForeground(new java.awt.Color(204, 204, 0));

        gB2.setBackground(new java.awt.Color(204, 204, 0));
        gB2.setForeground(new java.awt.Color(204, 204, 0));

        gB3.setBackground(new java.awt.Color(204, 204, 0));
        gB3.setForeground(new java.awt.Color(204, 204, 0));

        gB4.setBackground(new java.awt.Color(204, 204, 0));
        gB4.setForeground(new java.awt.Color(204, 204, 0));

        gB5.setBackground(new java.awt.Color(204, 204, 0));
        gB5.setForeground(new java.awt.Color(204, 204, 0));

        gC5.setBackground(new java.awt.Color(204, 204, 0));
        gC5.setForeground(new java.awt.Color(204, 204, 0));

        gC4.setBackground(new java.awt.Color(204, 204, 0));
        gC4.setForeground(new java.awt.Color(204, 204, 0));

        gC3.setBackground(new java.awt.Color(204, 204, 0));
        gC3.setForeground(new java.awt.Color(204, 204, 0));

        gC2.setBackground(new java.awt.Color(204, 204, 0));
        gC2.setForeground(new java.awt.Color(204, 204, 0));

        gC1.setBackground(new java.awt.Color(204, 204, 0));
        gC1.setForeground(new java.awt.Color(204, 204, 0));

        sD10.setBackground(new java.awt.Color(204, 204, 204));
        sD10.setForeground(new java.awt.Color(204, 204, 204));

        sD9.setBackground(new java.awt.Color(204, 204, 204));
        sD9.setForeground(new java.awt.Color(204, 204, 204));

        sD8.setBackground(new java.awt.Color(204, 204, 204));
        sD8.setForeground(new java.awt.Color(204, 204, 204));

        sD7.setBackground(new java.awt.Color(204, 204, 204));
        sD7.setForeground(new java.awt.Color(204, 204, 204));

        sD6.setBackground(new java.awt.Color(204, 204, 204));
        sD6.setForeground(new java.awt.Color(204, 204, 204));

        sE6.setBackground(new java.awt.Color(204, 204, 204));
        sE6.setForeground(new java.awt.Color(204, 204, 204));

        sE7.setBackground(new java.awt.Color(204, 204, 204));
        sE7.setForeground(new java.awt.Color(204, 204, 204));

        sE8.setBackground(new java.awt.Color(204, 204, 204));
        sE8.setForeground(new java.awt.Color(204, 204, 204));

        sE9.setBackground(new java.awt.Color(204, 204, 204));
        sE9.setForeground(new java.awt.Color(204, 204, 204));

        sE10.setBackground(new java.awt.Color(204, 204, 204));
        sE10.setForeground(new java.awt.Color(204, 204, 204));

        sD5.setBackground(new java.awt.Color(204, 204, 204));
        sD5.setForeground(new java.awt.Color(204, 204, 204));

        sD4.setBackground(new java.awt.Color(204, 204, 204));
        sD4.setForeground(new java.awt.Color(204, 204, 204));

        sD3.setBackground(new java.awt.Color(204, 204, 204));
        sD3.setForeground(new java.awt.Color(204, 204, 204));

        sD2.setBackground(new java.awt.Color(204, 204, 204));
        sD2.setForeground(new java.awt.Color(204, 204, 204));

        sD1.setBackground(new java.awt.Color(204, 204, 204));
        sD1.setForeground(new java.awt.Color(204, 204, 204));

        sE1.setBackground(new java.awt.Color(204, 204, 204));
        sE1.setForeground(new java.awt.Color(204, 204, 204));

        sE2.setBackground(new java.awt.Color(204, 204, 204));
        sE2.setForeground(new java.awt.Color(204, 204, 204));

        sE3.setBackground(new java.awt.Color(204, 204, 204));
        sE3.setForeground(new java.awt.Color(204, 204, 204));

        sE4.setBackground(new java.awt.Color(204, 204, 204));
        sE4.setForeground(new java.awt.Color(204, 204, 204));

        sE5.setBackground(new java.awt.Color(204, 204, 204));
        sE5.setForeground(new java.awt.Color(204, 204, 204));

        sF1.setBackground(new java.awt.Color(204, 204, 204));
        sF1.setForeground(new java.awt.Color(204, 204, 204));

        sF2.setBackground(new java.awt.Color(204, 204, 204));
        sF2.setForeground(new java.awt.Color(204, 204, 204));

        sF3.setBackground(new java.awt.Color(204, 204, 204));
        sF3.setForeground(new java.awt.Color(204, 204, 204));

        sF4.setBackground(new java.awt.Color(204, 204, 204));
        sF4.setForeground(new java.awt.Color(204, 204, 204));

        sF5.setBackground(new java.awt.Color(204, 204, 204));
        sF5.setForeground(new java.awt.Color(204, 204, 204));

        sF6.setBackground(new java.awt.Color(204, 204, 204));
        sF6.setForeground(new java.awt.Color(204, 204, 204));

        sF7.setBackground(new java.awt.Color(204, 204, 204));
        sF7.setForeground(new java.awt.Color(204, 204, 204));

        sF8.setBackground(new java.awt.Color(204, 204, 204));
        sF8.setForeground(new java.awt.Color(204, 204, 204));

        sF9.setBackground(new java.awt.Color(204, 204, 204));
        sF9.setForeground(new java.awt.Color(204, 204, 204));

        sF10.setBackground(new java.awt.Color(204, 204, 204));
        sF10.setForeground(new java.awt.Color(204, 204, 204));

        bG10.setBackground(new java.awt.Color(153, 102, 0));
        bG10.setForeground(new java.awt.Color(204, 204, 204));

        bG9.setBackground(new java.awt.Color(153, 102, 0));
        bG9.setForeground(new java.awt.Color(204, 204, 204));

        bG8.setBackground(new java.awt.Color(153, 102, 0));
        bG8.setForeground(new java.awt.Color(204, 204, 204));

        bG7.setBackground(new java.awt.Color(153, 102, 0));
        bG7.setForeground(new java.awt.Color(204, 204, 204));

        bG6.setBackground(new java.awt.Color(153, 102, 0));
        bG6.setForeground(new java.awt.Color(204, 204, 204));

        bG5.setBackground(new java.awt.Color(153, 102, 0));
        bG5.setForeground(new java.awt.Color(204, 204, 204));

        bG4.setBackground(new java.awt.Color(153, 102, 0));
        bG4.setForeground(new java.awt.Color(204, 204, 204));

        bG3.setBackground(new java.awt.Color(153, 102, 0));
        bG3.setForeground(new java.awt.Color(204, 204, 204));

        bG2.setBackground(new java.awt.Color(153, 102, 0));
        bG2.setForeground(new java.awt.Color(204, 204, 204));

        bG1.setBackground(new java.awt.Color(153, 102, 0));
        bG1.setForeground(new java.awt.Color(204, 204, 204));

        bH1.setBackground(new java.awt.Color(153, 102, 0));
        bH1.setForeground(new java.awt.Color(204, 204, 204));

        bH2.setBackground(new java.awt.Color(153, 102, 0));
        bH2.setForeground(new java.awt.Color(204, 204, 204));

        bH3.setBackground(new java.awt.Color(153, 102, 0));
        bH3.setForeground(new java.awt.Color(204, 204, 204));

        bH4.setBackground(new java.awt.Color(153, 102, 0));
        bH4.setForeground(new java.awt.Color(204, 204, 204));

        bH5.setBackground(new java.awt.Color(153, 102, 0));
        bH5.setForeground(new java.awt.Color(204, 204, 204));

        bH6.setBackground(new java.awt.Color(153, 102, 0));
        bH6.setForeground(new java.awt.Color(204, 204, 204));

        bH7.setBackground(new java.awt.Color(153, 102, 0));
        bH7.setForeground(new java.awt.Color(204, 204, 204));

        bH8.setBackground(new java.awt.Color(153, 102, 0));
        bH8.setForeground(new java.awt.Color(204, 204, 204));

        bH9.setBackground(new java.awt.Color(153, 102, 0));
        bH9.setForeground(new java.awt.Color(204, 204, 204));

        bH10.setBackground(new java.awt.Color(153, 102, 0));
        bH10.setForeground(new java.awt.Color(204, 204, 204));

        bI10.setBackground(new java.awt.Color(153, 102, 0));
        bI10.setForeground(new java.awt.Color(204, 204, 204));

        bI9.setBackground(new java.awt.Color(153, 102, 0));
        bI9.setForeground(new java.awt.Color(204, 204, 204));

        bI8.setBackground(new java.awt.Color(153, 102, 0));
        bI8.setForeground(new java.awt.Color(204, 204, 204));

        bI7.setBackground(new java.awt.Color(153, 102, 0));
        bI7.setForeground(new java.awt.Color(204, 204, 204));

        bI6.setBackground(new java.awt.Color(153, 102, 0));
        bI6.setForeground(new java.awt.Color(204, 204, 204));

        bI5.setBackground(new java.awt.Color(153, 102, 0));
        bI5.setForeground(new java.awt.Color(204, 204, 204));

        bI4.setBackground(new java.awt.Color(153, 102, 0));
        bI4.setForeground(new java.awt.Color(204, 204, 204));

        bI3.setBackground(new java.awt.Color(153, 102, 0));
        bI3.setForeground(new java.awt.Color(204, 204, 204));

        bI2.setBackground(new java.awt.Color(153, 102, 0));
        bI2.setForeground(new java.awt.Color(204, 204, 204));

        bI1.setBackground(new java.awt.Color(153, 102, 0));
        bI1.setForeground(new java.awt.Color(204, 204, 204));

        jButton1.setText("New Concert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concertClick(evt);
            }
        });

        javax.swing.GroupLayout concertPanelLayout = new javax.swing.GroupLayout(concertPanel);
        concertPanel.setLayout(concertPanelLayout);
        concertPanelLayout.setHorizontalGroup(
            concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(concertPanelLayout.createSequentialGroup()
                .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(concertPanelLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(concertPanelLayout.createSequentialGroup()
                                .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(concertPanelLayout.createSequentialGroup()
                                        .addComponent(gA10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(gA9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(gA8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(concertPanelLayout.createSequentialGroup()
                                        .addComponent(gB10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(gB9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(gB8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, concertPanelLayout.createSequentialGroup()
                                        .addComponent(gA7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(gA6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, concertPanelLayout.createSequentialGroup()
                                        .addComponent(gB7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(gB6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(concertPanelLayout.createSequentialGroup()
                                .addComponent(gC10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(gC9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(gC8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(gC7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(gC6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(concertPanelLayout.createSequentialGroup()
                                .addComponent(sD10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sD9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sD8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sD7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sD6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(concertPanelLayout.createSequentialGroup()
                                .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(concertPanelLayout.createSequentialGroup()
                                        .addComponent(sE10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sE9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sE8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sE7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(concertPanelLayout.createSequentialGroup()
                                        .addComponent(sF10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sF9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sF8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sF7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sF6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sE6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, concertPanelLayout.createSequentialGroup()
                                .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(concertPanelLayout.createSequentialGroup()
                                        .addComponent(bG10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bG9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bG8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bG7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(concertPanelLayout.createSequentialGroup()
                                        .addComponent(bH10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bH9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bH8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bH7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bH6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bG6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, concertPanelLayout.createSequentialGroup()
                                .addComponent(bI10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bI9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bI8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bI7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bI6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(concertPanelLayout.createSequentialGroup()
                                .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, concertPanelLayout.createSequentialGroup()
                                        .addComponent(gA5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(gA4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, concertPanelLayout.createSequentialGroup()
                                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(gB5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(gC5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gB4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(gC4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, concertPanelLayout.createSequentialGroup()
                                            .addComponent(gA3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(gA2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(gA1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, concertPanelLayout.createSequentialGroup()
                                            .addComponent(gB3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(gB2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(gB1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(concertPanelLayout.createSequentialGroup()
                                        .addComponent(gC3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(gC2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(gC1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(concertPanelLayout.createSequentialGroup()
                                .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sD5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sE5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sD4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sE4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(concertPanelLayout.createSequentialGroup()
                                        .addComponent(sD3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sD2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sD1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(concertPanelLayout.createSequentialGroup()
                                        .addComponent(sE3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sE2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sE1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, concertPanelLayout.createSequentialGroup()
                                .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sF5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bG5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(concertPanelLayout.createSequentialGroup()
                                        .addComponent(sF4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sF3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sF2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sF1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(concertPanelLayout.createSequentialGroup()
                                        .addComponent(bG4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bG3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bG2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bG1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, concertPanelLayout.createSequentialGroup()
                                .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bI5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bH5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(concertPanelLayout.createSequentialGroup()
                                        .addComponent(bH4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bH3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bH2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bH1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(concertPanelLayout.createSequentialGroup()
                                        .addComponent(bI4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bI3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bI2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bI1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(concertPanelLayout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(jButton1)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        concertPanelLayout.setVerticalGroup(
            concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(concertPanelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(concertPanelLayout.createSequentialGroup()
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gA1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gA2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gA5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gA4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gA3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gB1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gB2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gB4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gB3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gB5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(gC5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gC4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gC3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(gC2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gC1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sD5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sD4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sD2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sD3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sD1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sE5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sE4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sE3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sE2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sE1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sF1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sF2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sF3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sF4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sF5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bG5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bG4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bG3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bG2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bG1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bH1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bH2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bH3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bH4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bH5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bI5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bI4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bI3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bI2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bI1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(concertPanelLayout.createSequentialGroup()
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gA6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gA7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gA9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gA8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gA10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gB6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gB8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gB7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gB10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gB9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gC10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gC9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gC8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gC7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gC6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sD10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sD9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sD8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sD6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sD7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sE10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sE9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sE8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sE7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sE6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sF6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sF7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sF8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sF9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sF10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bG10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bG9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bG8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bG7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bG6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bH6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bH7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bH8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bH9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bH10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(concertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bI10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bI9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bI8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bI7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bI6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(concertPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(concertPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /*Clicking the button allows the user to enter booking details
    to an array and print them to the "Bookings.txt" file using the
    printToBookings method in the FileAccess class.
    */
    FileAccess myAccessor = new FileAccess();
    private void buttonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClick
        name = JOptionPane.showInputDialog("Please enter your name");
        seat = JOptionPane.showInputDialog("Please enter your Seat");
        myAccessor.printToBookings(name,seat);
    }//GEN-LAST:event_buttonClick
    
    /*This method allows the admin to create a new concert and store
    the details in the "ConcertDetails.txt" file. Every time a new concert is
    created the last one is deleted from the file i.e. it only stores the
    current concert.
    */
    private void concertClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concertClick
        concert = JOptionPane.showInputDialog("What is this concert called?");
        concertDate = JOptionPane.showInputDialog("What is the date of the concert?");
        goldPrice = Double.parseDouble((String)JOptionPane.showInputDialog("Please enter the gold seat price:"));
        silverPrice = Double.parseDouble((String)JOptionPane.showInputDialog("Please enter the silver seat price:"));
        bronzePrice = Double.parseDouble((String)JOptionPane.showInputDialog("Please enter the bronze seat price:"));
        myAccessor.printToConcertDetails(concert,concertDate,goldPrice,silverPrice,bronzePrice);
    }//GEN-LAST:event_concertClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConcertUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConcertUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConcertUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConcertUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConcertUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bG1;
    private javax.swing.JButton bG10;
    private javax.swing.JButton bG2;
    private javax.swing.JButton bG3;
    private javax.swing.JButton bG4;
    private javax.swing.JButton bG5;
    private javax.swing.JButton bG6;
    private javax.swing.JButton bG7;
    private javax.swing.JButton bG8;
    private javax.swing.JButton bG9;
    private javax.swing.JButton bH1;
    private javax.swing.JButton bH10;
    private javax.swing.JButton bH2;
    private javax.swing.JButton bH3;
    private javax.swing.JButton bH4;
    private javax.swing.JButton bH5;
    private javax.swing.JButton bH6;
    private javax.swing.JButton bH7;
    private javax.swing.JButton bH8;
    private javax.swing.JButton bH9;
    private javax.swing.JButton bI1;
    private javax.swing.JButton bI10;
    private javax.swing.JButton bI2;
    private javax.swing.JButton bI3;
    private javax.swing.JButton bI4;
    private javax.swing.JButton bI5;
    private javax.swing.JButton bI6;
    private javax.swing.JButton bI7;
    private javax.swing.JButton bI8;
    private javax.swing.JButton bI9;
    private javax.swing.JPanel concertPanel;
    private javax.swing.JButton gA1;
    private javax.swing.JButton gA10;
    private javax.swing.JButton gA2;
    private javax.swing.JButton gA3;
    private javax.swing.JButton gA4;
    private javax.swing.JButton gA5;
    private javax.swing.JButton gA6;
    private javax.swing.JButton gA7;
    private javax.swing.JButton gA8;
    private javax.swing.JButton gA9;
    private javax.swing.JButton gB1;
    private javax.swing.JButton gB10;
    private javax.swing.JButton gB2;
    private javax.swing.JButton gB3;
    private javax.swing.JButton gB4;
    private javax.swing.JButton gB5;
    private javax.swing.JButton gB6;
    private javax.swing.JButton gB7;
    private javax.swing.JButton gB8;
    private javax.swing.JButton gB9;
    private javax.swing.JButton gC1;
    private javax.swing.JButton gC10;
    private javax.swing.JButton gC2;
    private javax.swing.JButton gC3;
    private javax.swing.JButton gC4;
    private javax.swing.JButton gC5;
    private javax.swing.JButton gC6;
    private javax.swing.JButton gC7;
    private javax.swing.JButton gC8;
    private javax.swing.JButton gC9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton sD1;
    private javax.swing.JButton sD10;
    private javax.swing.JButton sD2;
    private javax.swing.JButton sD3;
    private javax.swing.JButton sD4;
    private javax.swing.JButton sD5;
    private javax.swing.JButton sD6;
    private javax.swing.JButton sD7;
    private javax.swing.JButton sD8;
    private javax.swing.JButton sD9;
    private javax.swing.JButton sE1;
    private javax.swing.JButton sE10;
    private javax.swing.JButton sE2;
    private javax.swing.JButton sE3;
    private javax.swing.JButton sE4;
    private javax.swing.JButton sE5;
    private javax.swing.JButton sE6;
    private javax.swing.JButton sE7;
    private javax.swing.JButton sE8;
    private javax.swing.JButton sE9;
    private javax.swing.JButton sF1;
    private javax.swing.JButton sF10;
    private javax.swing.JButton sF2;
    private javax.swing.JButton sF3;
    private javax.swing.JButton sF4;
    private javax.swing.JButton sF5;
    private javax.swing.JButton sF6;
    private javax.swing.JButton sF7;
    private javax.swing.JButton sF8;
    private javax.swing.JButton sF9;
    // End of variables declaration//GEN-END:variables
}
